export const words = {
	comments: "评论",
	users: "评论用户",
	account: "本人账号与会话",
	search: "搜索评论正文",
	userSearch: "搜索昵称或邮箱",
	path: "文章评论路径（精确匹配）",
	approved: "已通过",
	waiting: "待审核",
	spam: "垃圾",
	all: "全部状态",
	refresh: "重新读取",
	edit: "保存正文",
	reply: "发送回复",
	remove: "删除评论",
	cancel: "取消",
	confirm: "确认操作",
	original: "原正文",
	context: "同一线程上下文",
	loading: "正在加载…",
	empty: "没有符合条件的记录",
	state: "用户状态",
	guest: "正常用户",
	banned: "已封禁",
	unverified: "未验证",
	administrator: "管理员",
	ban: "封禁用户",
	unban: "解除封禁",
	linked: "关联评论",
	profile: "保存本人资料",
	password: "验证并修改密码",
	sessions: "自己的后台会话",
	revoke: "撤销会话",
	prev: "上一页",
	next: "下一页",
	success: "操作已完成，已刷新相关数据。",
	concurrency:
		"提交前核对原值；评论及资料接口不支持原子条件更新，仍可能被其他管理页并发覆盖。",
	unknown:
		"请重新读取同一线程确认结果；核对后如确需再次发送，请明确建立新操作。",
	notifications:
		"审核回复及发送回复可能触发 Waline 原有通知；是否通知由服务端和用户设置决定。",
	security:
		"在 Waline 安全页管理二步验证与 Waline 登录；后台会话与 Waline 会话分别管理。",
	securityUnavailable: "此环境未配置 Waline 安全页入口，二步验证管理不可用。",
	deleteNotice:
		"Waline 会删除此评论，以及 pid 或 rid 指向此评论的回复。永久删除不能撤回。",
	current: "当前会话",
	resultUnknown: "已核对结果，建立新操作",
	nickname: "昵称",
	website: "个人网站（HTTP/HTTPS）",
	currentPassword: "当前密码",
	newPassword: "新密码（8–128字符）",
	code: "二步验证码（已启用时必填）",
	saving: "正在提交…",
	source: "当前数据源",
	noTwikoo: "仅连接服务端配置的 Waline；此处不包含公网 Twikoo 数据。",
	profileScope:
		"资料仅编辑昵称和个人网站；邮箱、注册和角色配置不在此表单中。已有网站不能以空值清除（上游限制）。",
	sessionsScope:
		"列表仅显示本人的后台会话，无原始凭据；撤销当前会话会立即退出后台。Waline 浏览器登录由其安全页管理。",
	reason: "对象与动作",
	total: "条",
	detail: "详情",
	threadPage: "线程页",
	check: "核对",
	confirmNotice: "确认后将通过当前数据源执行此动作。",
	keep: "失败时保留输入；回复结果待确认期间不允许重复提交。",
};
