BEGIN;

ALTER TABLE wl_users ADD COLUMN IF NOT EXISTS auth_version integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS dc_password_reset (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES wl_users(id) ON DELETE CASCADE,
  token_digest bytea NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
  requested_email varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz
);
CREATE INDEX IF NOT EXISTS dc_password_reset_user_idx ON dc_password_reset (user_id);
CREATE INDEX IF NOT EXISTS dc_password_reset_expires_idx ON dc_password_reset (expires_at);

CREATE TABLE IF NOT EXISTS dc_password_reset_limit (
  email_digest bytea PRIMARY KEY CHECK (octet_length(email_digest) = 32),
  window_started_at timestamptz NOT NULL,
  request_count integer NOT NULL,
  next_allowed_at timestamptz NOT NULL
);

CREATE OR REPLACE FUNCTION dc_password_auth_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.password IS DISTINCT FROM OLD.password OR NEW.email IS DISTINCT FROM OLD.email THEN
    NEW.auth_version := OLD.auth_version + 1;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS dc_password_auth_change_before ON wl_users;
CREATE TRIGGER dc_password_auth_change_before BEFORE UPDATE ON wl_users
FOR EACH ROW EXECUTE FUNCTION dc_password_auth_change();

CREATE OR REPLACE FUNCTION dc_password_reset_revoke() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.auth_version IS DISTINCT FROM OLD.auth_version THEN
    DELETE FROM dc_password_reset WHERE user_id = NEW.id;
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS dc_password_reset_revoke_after ON wl_users;
CREATE TRIGGER dc_password_reset_revoke_after AFTER UPDATE ON wl_users
FOR EACH ROW EXECUTE FUNCTION dc_password_reset_revoke();

COMMIT;
